name: CI Run
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: CI Run
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
          go-version: '1.23.x'
    
    - name: Build
      run: go build -v
      
    - name: Run Tests
      run: go test .
      timeout-minutes: 3
